apiVersion: v1
kind: Service

metadata:
  name: inventario-service

spec:
  # El Service enviará tráfico a los pods
  # que tengan la etiqueta app=inventario-app.
  selector:
    app: inventario-app

  ports:
    - name: http

      # Puerto por el que se accede al Service.
      port: 80

      # Envía el tráfico al puerto llamado "http"
      # del contenedor, que corresponde al 3000.
      targetPort: http

  # Permite exponer el Service desde Minikube.
  type: NodePort